#define yy_create_buffer socks_yy_create_buffer
#define yy_delete_buffer socks_yy_delete_buffer
#define yy_scan_buffer socks_yy_scan_buffer
#define yy_scan_string socks_yy_scan_string
#define yy_scan_bytes socks_yy_scan_bytes
#define yy_flex_debug socks_yy_flex_debug
#define yy_init_buffer socks_yy_init_buffer
#define yy_flush_buffer socks_yy_flush_buffer
#define yy_load_buffer_state socks_yy_load_buffer_state
#define yy_switch_to_buffer socks_yy_switch_to_buffer
#define yyin socks_yyin
#define yyleng socks_yyleng
#define yylex socks_yylex
#define yyout socks_yyout
#define yyrestart socks_yyrestart
#define yytext socks_yytext
#define yylineno socks_yylineno

#line 20 "lex.yy.c"
/*	$OpenBSD: flex.skl,v 1.5 1997/07/25 21:05:28 mickey Exp $	*/

/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /cvs/./src/usr.bin/lex/flex.skl,v 1.5 1997/07/25 21:05:28 mickey Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#ifdef __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT

#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 64
#define YY_END_OF_BUFFER 65
static yyconst short int yy_acclist[341] =
    {   0,
       21,   21,   57,   57,    8,    8,   65,   63,   64,   59,
       63,   64,   61,   64,   60,   63,   64,   58,   63,   64,
       63,   64,   63,   64,   63,   64,   63,   64,   63,   64,
       63,   64,   63,   64,   63,   64,   63,   64,   63,   64,
       63,   64,   63,   64,   63,   64,   63,   64,   63,   64,
       56,   63,   64,   63,   64,   21,   63,   64,   21,   58,
       63,   64,   21,   63,   64,   21,   63,   64,   21,   63,
       64,   21,   63,   64,   63,   64,   63,   64,   63,   64,
       63,   64,   63,   64,   63,   64,   57,   63,   64,   57,
       59,   63,   64,   57,   60,   63,   64,   57,   58,   63,

       64,   57,   63,   64,   57,   63,   64,   57,   63,   64,
       57,   63,   64,   63,   64,   63,   64,   63,   64,   63,
       64,    8,   63,   64,    8,   60,   63,   64,    8,   58,
       63,   64,    8,   63,   64,    8,   63,   64,    8,   63,
       64,    8,   63,   64,   63,   64,   63,   64,   63,   64,
       63,   64,   63,   64,   63,   64,   63,   64,   24,   63,
       64,   24,   63,   64,   24,   63,   64,   25,   63,   64,
       25,   63,   64,   25,   63,   64,   25,   63,   64,   25,
       63,   64,   25,   63,   64,   25,   63,   64,   25,   63,
       64,   33,   58,   63,   64,   33,   63,   64,   33,   63,

       64,   33,   63,   64,   33,   63,   64,   59,   60,   58,
       62,   18,   21,   21,   21,   58,   21,   21,   18,   21,
       21,   57,   57,   59,   57,   60,   57,   58,   57,   18,
       57,   57,    8,    8,   60,    8,   58,    8,    8,   18,
        8,   24,   25,   24,   25,   25,   25,   18,   25,   25,
       33,   58,   33,   33,   18,   33,   33,   48,   10,   11,
       19,   21,   21,   21,   19,   21,   57,   19,   57,    8,
        8,   19,   25,   19,   25,   33,   19,   33,   26,   17,
       47,   21,   21,   17,   21,   13,   40,   17,   57,   50,
        8,   17,   43,   23,   17,   25,   17,   33,   46,    1,

        2,   21,   21,   52,   41,   42,   21,   21,   22,   44,
       12,   54,   20,   21,   14,   49,   28,   27,    9,   37,
       45,    4,    5,   39,   34,    7,   16,   36,   29,   51,
        6,   55,   53,   32,   15,   35,    3,   38,   30,   31
    } ;

static yyconst short int yy_accept[455] =
    {   0,
        1,    1,    1,    1,    1,    2,    3,    3,    3,    3,
        3,    3,    3,    4,    5,    5,    5,    6,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    8,   10,   13,   15,   18,   21,   23,   25,   27,
       29,   31,   33,   35,   37,   39,   41,   43,   45,   47,
       49,   51,   54,   56,   59,   63,   66,   69,   72,   75,
       77,   79,   81,   83,   85,   87,   90,   94,   98,  102,
      105,  108,  111,  114,  116,  118,  120,  122,  125,  129,
      133,  136,  139,  142,  145,  147,  149,  151,  153,  155,
      157,  159,  162,  165,  168,  171,  174,  177,  180,  183,

      186,  189,  192,  196,  199,  202,  205,  208,  209,  210,
      211,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  213,  213,
      213,  213,  214,  215,  217,  218,  219,  221,  222,  222,
      222,  222,  222,  222,  222,  223,  225,  227,  229,  230,
      232,  233,  233,  233,  233,  233,  233,  234,  236,  238,
      239,  241,  242,  242,  242,  242,  242,  242,  242,  243,
      244,  246,  247,  248,  250,  251,  253,  254,  255,  257,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  259,  259,  259,  259,  259,  259,  260,

      261,  261,  262,  263,  264,  265,  267,  267,  267,  267,
      267,  267,  267,  268,  270,  270,  270,  270,  270,  270,
      271,  273,  273,  273,  273,  273,  273,  273,  274,  276,
      277,  279,  280,  280,  280,  280,  280,  280,  280,  280,
      281,  281,  281,  281,  281,  281,  281,  282,  282,  282,
      282,  282,  282,  283,  284,  286,  287,  287,  287,  287,
      287,  288,  290,  290,  291,  291,  291,  291,  293,  293,
      294,  294,  295,  295,  295,  297,  299,  300,  300,  300,
      300,  300,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  302,  302,  303,  304,  304,  304,

      304,  304,  304,  304,  304,  305,  305,  305,  305,  305,
      305,  306,  306,  306,  306,  306,  306,  306,  306,  306,
      306,  306,  307,  307,  307,  307,  307,  307,  307,  308,
      310,  310,  310,  310,  310,  310,  310,  310,  310,  311,
      311,  311,  311,  312,  312,  312,  312,  312,  312,  312,
      313,  313,  313,  313,  313,  313,  313,  313,  313,  315,
      315,  316,  316,  316,  316,  317,  317,  317,  317,  317,
      317,  317,  317,  317,  318,  319,  319,  319,  319,  319,
      320,  320,  320,  320,  320,  320,  320,  320,  321,  321,
      321,  322,  322,  323,  324,  324,  324,  325,  326,  326,

      327,  327,  327,  327,  327,  327,  328,  328,  329,  329,
      329,  329,  329,  329,  329,  330,  330,  330,  330,  330,
      330,  331,  331,  332,  332,  332,  333,  333,  333,  333,
      333,  333,  334,  334,  334,  334,  335,  335,  335,  336,
      337,  337,  338,  338,  338,  339,  339,  339,  339,  340,
      340,  340,  341,  341
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    1,    5,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    6,    1,    7,    7,    8,
        7,    9,   10,    7,    7,    7,    7,   11,    1,   12,
       13,   14,    1,    1,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
        1,   16,    1,    1,   17,    1,   18,   19,   20,   21,

       22,   23,   24,   25,   26,   15,   27,   28,   29,   30,
       31,   32,   33,   34,   35,   36,   37,   38,   39,   40,
       41,   15,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[42] =
    {   0,
        1,    2,    3,    1,    1,    4,    5,    5,    5,    5,
        2,    1,    1,    1,    6,    1,    1,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6
    } ;

static yyconst short int yy_base[464] =
    {   0,
        0,    0,   31,    0,   68,    0,   99,  101,  100,  105,
       35,   36,  139,  176,  102,  132,  213,  250,  126,  150,
      713,  712,   32,   34,  116,  153,  288,    0,  329,    0,
      722,  725,  719,  725,    0,  122,  717,  682,  690,   30,
      695,  676,  681,   84,  134,  692,   99,  682,  137,   27,
      686,  725,  680,    0,  163,  684,  675,  677,  681,  680,
      674,  683,  681,  684,  675,    0,  698,    0,  186,  696,
      664,  666,  670,  664,  141,  660,  662,    0,  187,  193,
      689,  657,  659,  663,  653,  656,  651,  654,  649,  652,
      669,  668,  725,  667,    0,  646,  644,  154,  169,  655,

      645,  649,  199,    0,  640,  642,  646,  669,    0,  218,
      725,  634,  638,  642,   96,  648,  630,  634,  628,  627,
      643,  193,  625,  625,  204,  622,  626,  725,  625,  634,
      637,    0,  224,  231,  620,  622,    0,  634,  621,  620,
      617,  611,  618,  616,    0,  643,    0,  235,  613,    0,
      625,  612,  605,  605,  605,  607,    0,  208,  255,  606,
        0,  618,  600,  604,  611,  598,  599,  610,  725,    0,
        0,  598,  595,    0,  609,  260,    0,  595,    0,  607,
      599,  603,  600,  218,  591,  583,  597,  589,  595,  590,
      576,  596,  582,  587,  576,  572,  235,  573,  725,  725,

      574,  725,  270,  585,  577,    0,  584,  574,  585,  567,
      579,  579,  570,    0,  568,  579,  576,  564,  562,  564,
        0,  574,  569,  556,  553,  554,  560,  557,    0,  556,
        0,  725,  557,  553,  564,  563,  558,  555,  251,  725,
      544,  548,  542,  547,  537,  542,  725,  546,  540,  529,
      547,  562,  364,  547,    0,  532,  543,  529,  541,  530,
      725,    0,  539,  725,  529,  525,  536,    0,  525,  725,
      526,  725,  524,  519,    0,    0,  725,  517,  522,  515,
      530,  725,  514,  518,  517,  524,  527,  523,  507,  521,
      513,  520,  507,  725,  347,  374,  502,  515,  516,  500,

      516,  502,  512,  501,  725,  496,  503,  510,  487,  509,
      725,  504,  498,  487,  496,  503,  502,  488,  486,  486,
      484,  725,  493,  483,  479,  486,  480,  476,  378,    0,
      477,  472,  476,  485,  471,  468,  473,  484,  725,  472,
      459,  461,  725,  479,  461,  465,  467,  466,  456,  725,
      463,  454,  466,  461,  457,  468,  450,  459,  382,  456,
      725,  463,  461,  445,  725,  458,  443,  456,  460,  273,
      450,  449,  444,  725,  725,  437,  454,  435,  448,  725,
      433,  429,  435,  428,  424,  438,  429,  725,  442,  435,
      725,  422,  725,  725,  431,  429,  725,  725,  431,  725,

      435,  424,  420,  419,  426,  725,  433,  725,  414,  418,
      440,  421,  424,  415,  725,  424,  425,  416,  413,  404,
      725,  404,  725,  392,  396,  725,  391,  384,  369,  356,
      354,  725,  246,  247,  246,  725,  246,  232,  725,  725,
      218,  725,  220,  224,  725,  189,  183,  173,  725,  144,
       35,  725,  725,  392,  398,  404,  407,  413,  419,  425,
      431,   38,  433
    } ;

static yyconst short int yy_def[464] =
    {   0,
      453,    1,    1,    3,  453,    5,    3,    3,    3,    3,
        3,    3,  454,  454,    3,    3,  455,  455,    3,    3,
        3,    3,    3,    3,    3,    3,  453,   27,  453,   29,
      453,  453,  453,  453,  456,  453,  453,  453,  453,  453,
      453,  453,  453,  453,  453,  453,  453,  453,  453,  453,
      453,  453,  453,  457,  457,  457,  457,  457,  457,  453,
      453,  453,  453,  453,  453,  458,  458,  459,  458,  458,
      458,  458,  458,  453,  453,  453,  453,  460,  461,  460,
      460,  460,  460,  460,  453,  453,  453,  453,  453,  453,
      453,  453,  453,  453,  462,  462,  462,  462,  462,  462,

      462,  462,  463,  463,  463,  463,  463,  453,  456,  453,
      453,  453,  453,  453,  453,  453,  453,  453,  453,  453,
      453,  453,  453,  453,  453,  453,  453,  453,  453,  453,
      453,  457,  457,  457,  457,  457,  457,  457,  453,  453,
      453,  453,  453,  453,  458,  458,  459,  458,  458,  458,
      458,  453,  453,  453,  453,  453,  460,  461,  460,  460,
      460,  460,  453,  453,  453,  453,  453,  453,  453,  462,
      462,  462,  462,  462,  462,  463,  463,  463,  463,  463,
      453,  453,  453,  453,  453,  453,  453,  453,  453,  453,
      453,  453,  453,  453,  453,  453,  453,  453,  453,  453,

      453,  453,  457,  457,  457,  457,  453,  453,  453,  453,
      453,  453,  458,  458,  453,  453,  453,  453,  453,  460,
      460,  453,  453,  453,  453,  453,  453,  462,  462,  463,
      463,  453,  453,  453,  453,  453,  453,  453,  453,  453,
      453,  453,  453,  453,  453,  453,  453,  453,  453,  453,
      453,  453,  457,  457,  457,  453,  453,  453,  453,  453,
      453,  458,  453,  453,  453,  453,  453,  460,  453,  453,
      453,  453,  453,  453,  462,  463,  453,  453,  453,  453,
      453,  453,  453,  453,  453,  453,  453,  453,  453,  453,
      453,  453,  453,  453,  453,  457,  457,  453,  453,  453,

      453,  453,  453,  453,  453,  453,  453,  453,  453,  453,
      453,  453,  453,  453,  453,  453,  453,  453,  453,  453,
      453,  453,  453,  453,  453,  453,  453,  453,  457,  457,
      453,  453,  453,  453,  453,  453,  453,  453,  453,  453,
      453,  453,  453,  453,  453,  453,  453,  453,  453,  453,
      453,  453,  453,  453,  453,  453,  453,  453,  457,  453,
      453,  453,  453,  453,  453,  453,  453,  453,  453,  453,
      453,  453,  453,  453,  453,  453,  453,  453,  453,  453,
      453,  453,  453,  453,  453,  453,  453,  453,  453,  453,
      453,  453,  453,  453,  453,  453,  453,  453,  453,  453,

      453,  453,  453,  453,  453,  453,  453,  453,  453,  453,
      453,  453,  453,  453,  453,  453,  453,  453,  453,  453,
      453,  453,  453,  453,  453,  453,  453,  453,  453,  453,
      453,  453,  453,  453,  453,  453,  453,  453,  453,  453,
      453,  453,  453,  453,  453,  453,  453,  453,  453,  453,
      453,  453,    0,  453,  453,  453,  453,  453,  453,  453,
      453,  453,  453
    } ;

static yyconst short int yy_nxt[767] =
    {   0,
       32,   33,   34,   32,   35,   32,   36,   36,   36,   36,
       32,   32,   32,   32,   32,   37,   32,   38,   39,   40,
       41,   42,   43,   32,   32,   44,   32,   45,   46,   32,
       32,   47,   32,   48,   32,   49,   50,   51,   32,   32,
       32,   52,   32,  170,   32,   32,   32,  129,   32,   32,
       32,   32,   32,   65,   65,  452,   32,  114,   32,   32,
      115,  130,   32,   88,   32,   88,   53,   32,   32,   33,
       34,   32,   35,   54,   55,   55,   55,   55,   32,   32,
       32,   32,   54,   37,   32,   54,   54,   54,   56,   54,
       57,   54,   54,   54,   54,   54,   54,   54,   54,   54,

       54,   54,   54,   58,   54,   59,   54,   54,   54,   32,
       32,   32,   32,  119,  120,   32,  124,   60,   61,   60,
       61,   74,   75,   76,  184,  185,   32,   77,  110,  110,
      110,  110,  125,   63,   64,   62,   32,   62,   63,   64,
       67,   34,   32,   68,   89,   69,   69,   69,   69,   85,
       90,   74,   75,   76,   70,   86,  127,   77,  153,  121,
       32,   71,   87,   32,  122,  451,  154,  128,  133,  134,
      134,  134,  134,   85,   72,  171,   73,   67,   34,   86,
       68,   89,   69,   69,   69,   69,   87,   90,  109,  171,
      171,   70,  148,  148,  148,  148,  450,  109,   71,  159,

      159,  159,  159,  449,  171,  176,  176,  176,  176,  109,
      448,   72,  192,   73,   33,   34,  193,   79,  109,   80,
       80,   80,   80,   32,  110,  110,  110,  110,   81,  196,
      203,  203,  203,  203,  197,   82,  133,  134,  134,  134,
      134,  148,  148,  148,  148,  447,  235,  446,   83,  236,
       84,   33,   34,  445,   79,  444,   80,   80,   80,   80,
       32,  159,  159,  159,  159,   81,  176,  176,  176,  176,
      249,  443,   82,  442,  250,  253,  203,  203,  203,  203,
      283,  393,  394,  441,  284,   83,  440,   84,   32,   33,
       34,   91,   35,   32,   36,   36,   36,   36,   32,   92,

       93,   94,   95,   37,   32,   95,   95,   95,   95,   96,
       97,   98,   95,   95,   95,   99,   95,  100,   95,   95,
       95,   95,   95,  101,   95,  102,   95,   95,   95,   32,
       33,   34,   32,   35,   32,  103,  103,  103,  103,   32,
       32,   32,   32,  104,   37,   32,  104,  104,  104,  104,
      104,  105,  104,  104,  104,  104,  104,  104,  104,  104,
      104,  104,  104,  104,  106,  104,  107,  104,  104,  104,
      296,  296,  296,  296,  326,  439,  327,  438,  328,  329,
      296,  296,  296,  296,  359,  359,  359,  359,  359,  359,
      359,  359,   66,   66,   66,   66,   66,   66,   78,   78,

       78,   78,   78,   78,  109,  109,  437,  109,  109,  109,
      132,  132,  132,  145,  145,  436,  145,  145,  145,  147,
      147,  435,  147,  147,  147,  157,  434,  433,  157,  157,
      157,  158,  158,  432,  158,  158,  158,  177,  177,  431,
      430,  429,  428,  427,  426,  425,  424,  423,  422,  421,
      420,  419,  418,  417,  416,  415,  414,  413,  412,  411,
      410,  409,  408,  407,  406,  405,  404,  403,  402,  401,
      400,  399,  398,  397,  396,  395,  392,  391,  390,  389,
      388,  387,  386,  385,  384,  383,  382,  381,  380,  379,
      378,  377,  376,  375,  374,  373,  372,  371,  370,  369,

      368,  367,  366,  365,  364,  363,  362,  361,  360,  358,
      357,  356,  355,  354,  353,  352,  351,  350,  349,  348,
      347,  346,  345,  344,  343,  342,  341,  340,  339,  338,
      337,  336,  335,  334,  333,  332,  331,  330,  325,  324,
      323,  322,  321,  320,  319,  318,  317,  316,  315,  314,
      313,  312,  311,  310,  309,  308,  307,  306,  305,  304,
      303,  302,  301,  300,  299,  298,  297,  295,  294,  293,
      292,  291,  290,  289,  288,  287,  286,  285,  282,  281,
      280,  279,  278,  277,  276,  275,  274,  273,  272,  271,
      270,  269,  268,  267,  266,  265,  264,  263,  262,  261,

      260,  259,  258,  257,  256,  255,  254,  252,  251,  248,
      247,  246,  245,  244,  243,  242,  241,  240,  239,  238,
      237,  234,  233,  232,  231,  230,  229,  171,  228,  227,
      226,  225,  224,  223,  222,  221,  220,  219,  218,  217,
      216,  215,  214,  213,  146,  212,  211,  210,  209,  208,
      207,  206,  205,  204,  202,  201,  200,  199,  198,  195,
      194,  191,  190,  189,  188,  187,  186,  183,  182,  181,
      108,  180,  179,  178,  175,  174,  173,  172,  171,  169,
      169,  169,  168,  167,  166,  165,  164,  163,  162,  161,
      160,  111,  156,  155,  152,  151,  150,  149,  111,  146,

      144,  143,  142,  141,  140,  139,  138,  137,  136,  135,
      128,  131,  126,  123,  118,  117,  116,  113,  112,  111,
      108,  453,   32,   32,   31,  453,  453,  453,  453,  453,
      453,  453,  453,  453,  453,  453,  453,  453,  453,  453,
      453,  453,  453,  453,  453,  453,  453,  453,  453,  453,
      453,  453,  453,  453,  453,  453,  453,  453,  453,  453,
      453,  453,  453,  453,  453,  453
    } ;

static yyconst short int yy_chk[767] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,   23,  462,   24,   11,   12,   50,    3,    3,
        3,    3,    3,   11,   12,  451,    3,   40,    3,    3,
       40,   50,    3,   23,    3,   24,    3,    3,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,

        5,    5,    5,    5,    5,    5,    5,    5,    5,    7,
        9,    8,   15,   44,   44,   10,   47,    7,    7,    8,
        8,   15,   15,   15,  115,  115,   25,   15,   36,   36,
       36,   36,   47,    9,    9,    7,   19,    8,   10,   10,
       13,   13,   16,   13,   25,   13,   13,   13,   13,   19,
       25,   16,   16,   16,   13,   19,   49,   16,   75,   45,
       20,   13,   19,   26,   45,  450,   75,   49,   55,   55,
       55,   55,   55,   20,   13,   98,   13,   14,   14,   20,
       14,   26,   14,   14,   14,   14,   20,   26,   79,   98,
       99,   14,   69,   69,   69,   69,  448,   79,   14,   80,

       80,   80,   80,  447,   99,  103,  103,  103,  103,  158,
      446,   14,  122,   14,   17,   17,  122,   17,  158,   17,
       17,   17,   17,   17,  110,  110,  110,  110,   17,  125,
      133,  133,  133,  133,  125,   17,  134,  134,  134,  134,
      134,  148,  148,  148,  148,  444,  184,  443,   17,  184,
       17,   18,   18,  441,   18,  438,   18,   18,   18,   18,
       18,  159,  159,  159,  159,   18,  176,  176,  176,  176,
      197,  437,   18,  435,  197,  203,  203,  203,  203,  203,
      239,  370,  370,  434,  239,   18,  433,   18,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,

       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
      253,  253,  253,  253,  295,  431,  295,  430,  295,  296,
      296,  296,  296,  296,  329,  329,  329,  329,  359,  359,
      359,  359,  454,  454,  454,  454,  454,  454,  455,  455,

      455,  455,  455,  455,  456,  456,  429,  456,  456,  456,
      457,  457,  457,  458,  458,  428,  458,  458,  458,  459,
      459,  427,  459,  459,  459,  460,  425,  424,  460,  460,
      460,  461,  461,  422,  461,  461,  461,  463,  463,  420,
      419,  418,  417,  416,  414,  413,  412,  411,  410,  409,
      407,  405,  404,  403,  402,  401,  399,  396,  395,  392,
      390,  389,  387,  386,  385,  384,  383,  382,  381,  379,
      378,  377,  376,  373,  372,  371,  369,  368,  367,  366,
      364,  363,  362,  360,  358,  357,  356,  355,  354,  353,
      352,  351,  349,  348,  347,  346,  345,  344,  342,  341,

      340,  338,  337,  336,  335,  334,  333,  332,  331,  328,
      327,  326,  325,  324,  323,  321,  320,  319,  318,  317,
      316,  315,  314,  313,  312,  310,  309,  308,  307,  306,
      304,  303,  302,  301,  300,  299,  298,  297,  293,  292,
      291,  290,  289,  288,  287,  286,  285,  284,  283,  281,
      280,  279,  278,  274,  273,  271,  269,  267,  266,  265,
      263,  260,  259,  258,  257,  256,  254,  252,  251,  250,
      249,  248,  246,  245,  244,  243,  242,  241,  238,  237,
      236,  235,  234,  233,  230,  228,  227,  226,  225,  224,
      223,  222,  220,  219,  218,  217,  216,  215,  213,  212,

      211,  210,  209,  208,  207,  205,  204,  201,  198,  196,
      195,  194,  193,  192,  191,  190,  189,  188,  187,  186,
      185,  183,  182,  181,  180,  178,  175,  173,  172,  168,
      167,  166,  165,  164,  163,  162,  160,  156,  155,  154,
      153,  152,  151,  149,  146,  144,  143,  142,  141,  140,
      139,  138,  136,  135,  131,  130,  129,  127,  126,  124,
      123,  121,  120,  119,  118,  117,  116,  114,  113,  112,
      108,  107,  106,  105,  102,  101,  100,   97,   96,   94,
       92,   91,   90,   89,   88,   87,   86,   85,   84,   83,
       82,   81,   77,   76,   74,   73,   72,   71,   70,   67,

       65,   64,   63,   62,   61,   60,   59,   58,   57,   56,
       53,   51,   48,   46,   43,   42,   41,   39,   38,   37,
       33,   31,   22,   21,  453,  453,  453,  453,  453,  453,
      453,  453,  453,  453,  453,  453,  453,  453,  453,  453,
      453,  453,  453,  453,  453,  453,  453,  453,  453,  453,
      453,  453,  453,  453,  453,  453,  453,  453,  453,  453,
      453,  453,  453,  453,  453,  453
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "config_scan.l"
#define INITIAL 0
/*
 * Copyright (c) 1997, 1998, 1999
 *      Inferno Nettverk A/S, Norway.  All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. The above copyright notice, this list of conditions and the following
 *    disclaimer must appear in all copies of the software, derivative works
 *    or modified versions, and any portions thereof, aswell as in all
 *    supporting documentation.
 * 2. All advertising materials mentioning features or use of this software
 *    must display the following acknowledgement:
 *      This product includes software developed by
 *      Inferno Nettverk A/S, Norway.
 * 3. The name of the author may not be used to endorse or promote products
 *    derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. 
 * IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT 
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * Inferno Nettverk A/S requests users of this software to return to
 * 
 *  Software Distribution Coordinator  or  sdc@inet.no
 *  Inferno Nettverk A/S
 *  Oslo Research Park
 *  Gaustadaléen 21
 *  N-0371 Oslo
 *  Norway
 * 
 * any improvements or extensions that they make and grant Inferno Nettverk A/S
 * the rights to redistribute these changes.
 *
 */
#line 45 "config_scan.l"

static const char rcsid[] =
"$Id: config_scan.l,v 1.35 1999/03/11 16:59:32 karls Exp $";

#include "common.h"

#include "yacconfig.h" 
#include "config_parse.h"


/*%option debug  */
/* startconditions */
#define lineprefix 1

#define start_address 2

#define start_command 3

#define start_compatibility 4

#define start_extension 5

#define start_line 6

#define start_log 7

#define start_logoutput 8

#define start_method 9

#define start_option 10

#define start_port 11

#define start_proxyprotocol 12

#define start_service 13

#define start_username 14

#line 837 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#ifdef __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 78 "config_scan.l"



	/*
	 * we can operate in more than one mode, find out which it is and
	 * let the parser know.
	*/



	extern int parseinit;
	extern const int configtype;

	if (!parseinit) {
		parseinit = 1;

		switch (configtype) {
			case CONFIGTYPE_SERVER:
				return SERVERCONFIG;

			case CONFIGTYPE_CLIENT:
				return CLIENTCONFIG;

			default:
				SERR(configtype);
		}
	}


	/*
	 * Config stuff. 
	*/




	/* generic */

#line 1027 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 454 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 725 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 116 "config_scan.l"
{
	yylval.string = yytext;
	return DEBUGING;
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 121 "config_scan.l"
{
	yylval.string = yytext;
	return ROUTE;
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 127 "config_scan.l"
{
	BEGIN(start_proxyprotocol);

	yylval.string = yytext;
	return PROXYPROTOCOL;
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 134 "config_scan.l"
{
	yylval.string = yytext;
	return PROXYPROTOCOL_SOCKS_V4;
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 139 "config_scan.l"
{
	yylval.string = yytext;
	return PROXYPROTOCOL_SOCKS_V5;
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 144 "config_scan.l"
{
	yylval.string = yytext;
	return PROXYPROTOCOL_MSPROXY_V2;
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 149 "config_scan.l"
{
	BEGIN(start_logoutput);

	yylval.string = yytext;
	return LOGOUTPUT;
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 156 "config_scan.l"
{
	yylval.string = yytext;
	return LOGFILE;
}
	YY_BREAK
/*
	 * protocol
	 */
case 9:
YY_RULE_SETUP
#line 165 "config_scan.l"
{
	yylval.string = yytext;
	return PROTOCOL; 
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 171 "config_scan.l"
{
	yylval.string = yytext;
	return PROTOCOL_TCP;
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 176 "config_scan.l"
{
	yylval.string = yytext;
	return PROTOCOL_UDP;
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 181 "config_scan.l"
{
	BEGIN(start_command);

	yylval.string = yytext;
	return COMMAND; 
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 188 "config_scan.l"
{
	yylval.string = yytext;
	return COMMAND_BIND; 
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 193 "config_scan.l"
{
	yylval.string = yytext;
	return COMMAND_CONNECT; 
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 198 "config_scan.l"
{
	yylval.string = yytext;
	return COMMAND_UDPASSOCIATE;
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 203 "config_scan.l"
{
	yylval.string = yytext;
	return COMMAND_BINDREPLY;
}
	YY_BREAK
/*
	 * addresses
	 */
case 17:
YY_RULE_SETUP
#line 214 "config_scan.l"
{
	BEGIN(start_address);

	yylval.string = yytext;
	return FROM; 
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 221 "config_scan.l"
{
	BEGIN(start_address);

	yylval.string = yytext;
	return TO; 
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 228 "config_scan.l"
{
	BEGIN(start_address);

	yylval.string = yytext;
	return VIA; 
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 237 "config_scan.l"
{ 
	BEGIN(start_port);
	
	yylval.string = yytext;
	return IPADDRESS; 
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 244 "config_scan.l"
{
	BEGIN(start_port);

	yylval.string = yytext;
	return DOMAIN;
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 251 "config_scan.l"
{
	yylval.string = yytext;
	return DIRECT;
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 257 "config_scan.l"
{
	BEGIN(start_service);

	yylval.string = yytext;
	return PORT; 
}
	YY_BREAK
/* compare */
case 24:
YY_RULE_SETUP
#line 265 "config_scan.l"
{
	yylval.string = yytext;
	return OPERATOR; 
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 270 "config_scan.l"
{
	BEGIN(0);

	yylval.string = yytext;
	return SERVICENAME;
}
	YY_BREAK
/*
	 * authentication
	*/
case 26:
YY_RULE_SETUP
#line 283 "config_scan.l"
{
	BEGIN(start_method);	/* identical names to method */

	yylval.string = yytext;
	return AUTH; 
}
	YY_BREAK
/* server configstuff */
case 27:
YY_RULE_SETUP
#line 295 "config_scan.l"
{
	BEGIN(start_address);

	yylval.string = yytext;
	return INTERNAL;
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 302 "config_scan.l"
{
	BEGIN(start_address);

	yylval.string = yytext;
	return EXTERNAL;
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 310 "config_scan.l"
{

	yylval.string = yytext;
	return PRIVILEGED;
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 316 "config_scan.l"
{
	BEGIN(start_username);

	yylval.string = yytext;
	return USER_PRIVILEGED;
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 323 "config_scan.l"
{
	BEGIN(start_username);

	yylval.string = yytext;
	return USER_UNPRIVILEGED;
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 330 "config_scan.l"
{
	BEGIN(start_username);

	yylval.string = yytext;
	return USER_LIBWRAP;
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 338 "config_scan.l"
{
	BEGIN(0);
	
	yylval.string = yytext;
	return USERNAME;
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 345 "config_scan.l"
{
	yylval.string = yytext;
	return IOTIMEOUT;
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 350 "config_scan.l"
{
	BEGIN(start_compatibility);

	yylval.string = yytext;
	return COMPATIBILITY;
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 357 "config_scan.l"
{
	yylval.string = yytext;
	return REUSEADDR;
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 362 "config_scan.l"
{
	yylval.string = yytext;
	return SAMEPORT;
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 368 "config_scan.l"
{
	yylval.string = yytext;
	return CONNECTTIMEOUT;
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 373 "config_scan.l"
{
	BEGIN(start_extension);

	yylval.string = yytext;
	return EXTENSION;
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 381 "config_scan.l"
{
	yylval.string = yytext;
	return BIND;
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 388 "config_scan.l"
{
	yylval.string = yytext;
	return CLIENT;
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 394 "config_scan.l"
{
	BEGIN(start_method);

	yylval.string = yytext;
	return METHOD;
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 401 "config_scan.l"
{
	yylval.string = yytext;
	return NONE;
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 406 "config_scan.l"
{
	yylval.string = yytext;
	return GSSAPI;
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 411 "config_scan.l"
{
	yylval.string = yytext;
	return UNAME;
}
	YY_BREAK
/* filterrules */
/*
	 * verdicts
 	*/
case 46:
YY_RULE_SETUP
#line 423 "config_scan.l"
{
	yylval.string = yytext;
	return VERDICT_BLOCK;
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 428 "config_scan.l"
{
	yylval.string = yytext;
	return VERDICT_PASS;
}
	YY_BREAK
/*
	 * logging 
	 */
case 48:
YY_RULE_SETUP
#line 439 "config_scan.l"
{
	BEGIN(start_log);

	yylval.string = yytext;
	return LOG;  
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 446 "config_scan.l"
{
	yylval.string = yytext;
	return LOG_CONNECT;
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 451 "config_scan.l"
{
	yylval.string = yytext;
	return LOG_DATA;
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 456 "config_scan.l"
{
	yylval.string = yytext;
	return LOG_DISCONNECT;
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 461 "config_scan.l"
{
	yylval.string = yytext;
	return LOG_ERROR;
}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 466 "config_scan.l"
{
	yylval.string = yytext;
	return LOG_IOOPERATION;
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 471 "config_scan.l"
{
	BEGIN(lineprefix); 

	yylval.string = yytext;
	return LIBWRAPSTART;
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 478 "config_scan.l"
{
	BEGIN(lineprefix); 

	yylval.string = yytext;
	return LOCALDOMAIN;  
}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 485 "config_scan.l"
{
	BEGIN(start_line);

	yylval.string = yytext;
	return *yytext;
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 492 "config_scan.l"
{
	BEGIN(0);

	yylval.string = yytext;
	return LINE;
}
	YY_BREAK
/* misc generic stuff. */
case 58:
YY_RULE_SETUP
#line 506 "config_scan.l"
{
	yylval.string = yytext;
	return NUMBER;
}
	YY_BREAK
/* ignored */
case 59:
YY_RULE_SETUP
#line 513 "config_scan.l"
{
	;
}
	YY_BREAK
/* shell style comment */
case 60:
YY_RULE_SETUP
#line 518 "config_scan.l"
{
	;
}
	YY_BREAK
/* state always ends at eol. */
case 61:
YY_RULE_SETUP
#line 523 "config_scan.l"
{
	BEGIN(0);
}
	YY_BREAK
/* unless it's escaped. */
case 62:
YY_RULE_SETUP
#line 528 "config_scan.l"
{
	;
}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 532 "config_scan.l"
{
	return *yytext;
}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 537 "config_scan.l"
ECHO;
	YY_BREAK
#line 1696 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
			case YY_STATE_EOF(lineprefix):
			case YY_STATE_EOF(start_address):
			case YY_STATE_EOF(start_command):
			case YY_STATE_EOF(start_compatibility):
			case YY_STATE_EOF(start_extension):
			case YY_STATE_EOF(start_line):
			case YY_STATE_EOF(start_log):
			case YY_STATE_EOF(start_logoutput):
			case YY_STATE_EOF(start_method):
			case YY_STATE_EOF(start_option):
			case YY_STATE_EOF(start_port):
			case YY_STATE_EOF(start_proxyprotocol):
			case YY_STATE_EOF(start_service):
			case YY_STATE_EOF(start_username):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 454 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 454 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 453);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 537 "config_scan.l"
