#define yy_create_buffer socks_yy_create_buffer
#define yy_delete_buffer socks_yy_delete_buffer
#define yy_scan_buffer socks_yy_scan_buffer
#define yy_scan_string socks_yy_scan_string
#define yy_scan_bytes socks_yy_scan_bytes
#define yy_flex_debug socks_yy_flex_debug
#define yy_init_buffer socks_yy_init_buffer
#define yy_flush_buffer socks_yy_flush_buffer
#define yy_load_buffer_state socks_yy_load_buffer_state
#define yy_switch_to_buffer socks_yy_switch_to_buffer
#define yyin socks_yyin
#define yyleng socks_yyleng
#define yylex socks_yylex
#define yyout socks_yyout
#define yyrestart socks_yyrestart
#define yytext socks_yytext
#define yylineno socks_yylineno

#line 20 "lex.yy.c"
/*	$OpenBSD: flex.skl,v 1.5 1997/07/25 21:05:28 mickey Exp $	*/

/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /cvs/src/usr.bin/lex/flex.skl,v 1.5 1997/07/25 21:05:28 mickey Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#ifdef __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT

#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 61
#define YY_END_OF_BUFFER 62
static yyconst short int yy_acclist[311] =
    {   0,
       54,   54,    5,    5,   62,   60,   61,   56,   60,   61,
       58,   61,   57,   60,   61,   55,   60,   61,   60,   61,
       60,   61,   60,   61,   60,   61,   60,   61,   60,   61,
       60,   61,   60,   61,   60,   61,   60,   61,   60,   61,
       60,   61,   60,   61,   60,   61,   60,   61,   53,   60,
       61,   60,   61,   60,   61,   55,   60,   61,   60,   61,
       60,   61,   60,   61,   60,   61,   60,   61,   60,   61,
       60,   61,   60,   61,   60,   61,   60,   61,   60,   61,
       60,   61,   54,   60,   61,   54,   56,   60,   61,   54,
       57,   60,   61,   54,   55,   60,   61,   54,   60,   61,

       54,   60,   61,   54,   60,   61,   54,   60,   61,   60,
       61,   60,   61,   60,   61,   60,   61,    5,   60,   61,
        5,   57,   60,   61,    5,   55,   60,   61,    5,   60,
       61,    5,   60,   61,    5,   60,   61,    5,   60,   61,
       60,   61,   60,   61,   60,   61,   60,   61,   21,   60,
       61,   21,   60,   61,   21,   60,   61,   22,   60,   61,
       22,   60,   61,   22,   60,   61,   22,   60,   61,   22,
       60,   61,   22,   60,   61,   22,   60,   61,   22,   60,
       61,   30,   55,   60,   61,   30,   60,   61,   30,   60,
       61,   30,   60,   61,   30,   60,   61,   56,   57,   55,

       59,   15,   55,   15,   54,   54,   56,   54,   57,   54,
       55,   54,   15,   54,   54,    5,    5,   57,    5,   55,
        5,    5,   15,    5,   21,   22,   21,   22,   22,   22,
       15,   22,   22,   30,   55,   30,   30,   15,   30,   30,
       45,    7,    8,   16,   18,   16,   54,   16,   54,    5,
        5,   16,   22,   16,   22,   30,   16,   30,   23,   14,
       44,   18,   14,   20,   10,   37,   14,   54,   47,    5,
       14,   40,   14,   22,   14,   30,   43,    1,    2,   49,
       38,   39,   19,   41,    9,   51,   17,   11,   46,   25,
       24,    6,   34,   42,   36,   31,    4,   13,   33,   26,

       48,   52,   50,   29,   12,   32,   35,    3,   27,   28
    } ;

static yyconst short int yy_accept[438] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    2,    3,    3,    3,    4,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    6,    8,   11,
       13,   16,   19,   21,   23,   25,   27,   29,   31,   33,
       35,   37,   39,   41,   43,   45,   47,   49,   52,   54,
       56,   59,   61,   63,   65,   67,   69,   71,   73,   75,
       77,   79,   81,   83,   86,   90,   94,   98,  101,  104,
      107,  110,  112,  114,  116,  118,  121,  125,  129,  132,
      135,  138,  141,  143,  145,  147,  149,  152,  155,  158,
      161,  164,  167,  170,  173,  176,  179,  182,  186,  189,

      192,  195,  198,  199,  200,  201,  202,  202,  202,  202,
      202,  202,  202,  202,  202,  202,  202,  202,  202,  202,
      202,  202,  202,  203,  203,  203,  203,  203,  203,  203,
      203,  203,  204,  204,  204,  204,  204,  204,  205,  205,
      205,  205,  205,  205,  205,  205,  206,  208,  210,  212,
      213,  215,  216,  216,  216,  216,  216,  216,  217,  219,
      221,  222,  224,  225,  225,  225,  225,  226,  227,  229,
      230,  231,  233,  234,  236,  237,  238,  240,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  242,  242,  242,  242,  242,  242,  243,  244,  244,

      245,  245,  246,  246,  246,  246,  246,  247,  247,  247,
      247,  247,  247,  247,  248,  250,  250,  250,  250,  250,
      250,  251,  253,  253,  253,  253,  254,  256,  257,  259,
      260,  260,  260,  260,  260,  260,  260,  260,  261,  261,
      261,  261,  261,  261,  261,  262,  262,  262,  262,  262,
      263,  263,  263,  264,  265,  266,  266,  266,  266,  266,
      267,  269,  269,  270,  270,  270,  270,  272,  272,  273,
      273,  275,  277,  278,  278,  278,  278,  278,  279,  279,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  280,
      280,  280,  280,  280,  280,  280,  280,  280,  280,  280,

      281,  281,  281,  281,  282,  282,  282,  282,  282,  282,
      282,  282,  282,  282,  282,  283,  283,  283,  283,  283,
      283,  283,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  285,  285,  286,  286,  286,  286,  286,  286,  286,
      287,  287,  287,  287,  287,  287,  287,  287,  288,  288,
      289,  289,  289,  289,  290,  290,  290,  290,  290,  290,
      290,  291,  292,  292,  292,  292,  292,  293,  293,  293,
      293,  293,  293,  293,  294,  294,  294,  295,  295,  295,
      296,  297,  297,  298,  298,  298,  298,  298,  298,  299,
      299,  300,  300,  300,  300,  300,  300,  301,  301,  301,

      301,  301,  301,  302,  302,  302,  302,  303,  303,  303,
      303,  303,  303,  304,  304,  304,  304,  305,  305,  305,
      306,  307,  307,  307,  307,  307,  308,  308,  308,  308,
      309,  309,  310,  310,  310,  311,  311
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    1,    5,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    6,    1,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    8,    1,    9,
       10,   11,    1,    1,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
        1,   13,    1,    1,    1,    1,   14,   15,   16,   17,

       18,   19,   20,   21,   22,   23,   24,   25,   26,   27,
       28,   29,   30,   31,   32,   33,   34,   35,   36,   37,
       38,   23,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[39] =
    {   0,
        1,    2,    3,    1,    1,    4,    5,    2,    1,    1,
        1,    6,    1,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6
    } ;

static yyconst short int yy_base[452] =
    {   0,
        0,    0,   31,    0,   65,    0,   96,   98,   97,  102,
       35,   36,  133,  167,   99,  131,  201,  235,  117,  123,
      672,  671,  270,    0,  308,  343,  678,  681,  675,  681,
        0,  669,  672,  640,  648,   27,  654,  634,  639,   13,
       96,  651,   28,  640,   92,  109,  645,  681,  638,  148,
      116,  659,  136,  150,  139,  155,  153,  642,  635,  645,
      643,  646,  637,    0,  656,    0,  650,  653,  624,  626,
      631,  624,  105,  620,  622,    0,  163,  642,  645,  616,
      618,  623,  612,  615,  610,  631,  630,  681,  629,    0,
      608,  606,  144,  145,  618,  607,  612,  626,    0,  601,

      603,  608,  627,    0,  621,  681,  594,  598,  603,  158,
      609,  590,  594,  588,  587,  604,   38,  585,  585,  151,
      582,  586,  681,  585,  595,  598,  170,  181,  183,  185,
      204,  192,  605,  206,  188,  195,  190,  604,  201,  582,
      581,  578,  572,  579,  577,    0,  601,    0,  595,  573,
        0,  586,  572,  565,  565,  565,  567,    0,  220,  587,
      565,    0,  578,  559,  563,  571,  681,    0,    0,  560,
      557,    0,  572,  578,    0,  556,    0,  569,  561,  565,
      562,  198,  552,  544,  559,  550,  557,  552,  537,  558,
      543,  549,  537,  533,  534,  533,  681,  681,  534,  681,

      219,  223,  238,  199,  220,  226,  558,  546,  535,  547,
      528,  541,  541,  531,    0,  529,  541,  538,  525,  523,
      525,    0,  536,  531,  517,  521,    0,  520,    0,  681,
      521,  517,  529,  528,  523,  520,  220,  681,  508,  512,
      506,  511,  501,  506,  681,  511,  504,  513,  524,  227,
      246,  249,  523,  522,  496,  508,  493,  506,  494,  681,
        0,  504,  681,  493,  489,  501,    0,  489,  681,  490,
        0,    0,  681,  483,  488,  481,  497,  681,  480,  484,
      483,  491,  494,  490,  473,  488,  479,  487,  681,  235,
      250,  322,  484,  485,  468,  485,  470,  481,  469,  681,

      464,  472,  479,  681,  475,  469,  457,  467,  474,  473,
      458,  456,  456,  454,  681,  464,  453,  458,  451,  447,
      470,  470,  446,  441,  445,  455,  440,  437,  442,  454,
      681,  441,  681,  451,  432,  436,  438,  437,  427,  681,
      434,  425,  438,  432,  441,  422,  432,  446,  427,  681,
      435,  433,  416,  681,  430,  414,  428,  423,  422,  415,
      681,  681,  403,  415,  390,  404,  382,  375,  370,  342,
      337,  352,  342,  681,  356,  349,  681,  345,  343,  681,
      681,  346,  681,  350,  348,  334,  333,  341,  681,  347,
      681,  327,  331,  336,  339,  315,  681,  309,  325,  316,

      312,  303,  681,  308,  301,  305,  681,  300,  302,  295,
      311,  308,  681,  287,  290,  301,  681,  300,  300,  681,
      681,  236,  239,  241,  245,  681,  234,  231,  224,  681,
      144,  681,   91,   46,  681,  681,  378,  384,  390,  396,
      399,  402,  408,  414,  420,  426,   55,  428,  431,  434,
      437
    } ;

static yyconst short int yy_def[452] =
    {   0,
      436,    1,    1,    3,  436,    5,    3,    3,    3,    3,
        3,    3,  437,  437,    3,    3,  438,  438,    3,    3,
        3,    3,  436,   23,  439,  439,  436,  436,  436,  436,
      440,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  441,
      442,  442,  442,  442,  442,  442,  442,  436,  436,  436,
      436,  436,  436,  443,  443,  444,  443,  443,  443,  443,
      443,  436,  436,  436,  436,  445,  446,  445,  445,  445,
      445,  445,  436,  436,  436,  436,  436,  436,  436,  447,
      447,  447,  447,  447,  447,  447,  447,  448,  448,  448,

      448,  448,  436,  440,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  449,  441,  441,  450,
      441,  442,  442,  441,  442,  442,  442,  442,  442,  436,
      436,  436,  436,  436,  436,  443,  443,  444,  443,  443,
      443,  443,  436,  436,  436,  436,  436,  445,  446,  445,
      445,  445,  445,  436,  436,  436,  436,  447,  447,  447,
      447,  447,  447,  448,  448,  448,  448,  448,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,

      451,  450,  441,  442,  442,  442,  442,  436,  436,  436,
      436,  436,  436,  443,  443,  436,  436,  436,  436,  436,
      445,  445,  436,  436,  436,  447,  447,  448,  448,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  451,
      449,  442,  442,  442,  436,  436,  436,  436,  436,  436,
      443,  436,  436,  436,  436,  436,  445,  436,  436,  436,
      447,  448,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  442,  436,  436,  436,  436,  436,  436,  436,  436,

      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  442,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,

      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,    0,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436
    } ;

static yyconst short int yy_nxt[720] =
    {   0,
       28,   29,   30,   28,   31,   28,   32,   28,   28,   28,
       28,   28,   33,   34,   35,   36,   37,   38,   39,   28,
       28,   40,   28,   28,   41,   42,   28,   28,   43,   28,
       44,   28,   45,   46,   47,   28,   28,   28,   48,  114,
      115,  119,   28,   28,   28,   28,   28,   28,   28,   63,
       63,  109,   28,  190,  110,   28,   28,  191,  120,   28,
      168,   28,  435,   49,   28,   28,   29,   30,   28,   31,
       50,   51,   28,   28,   28,   28,   52,   33,   52,   52,
       52,   53,   52,   54,   52,   52,   52,   52,   52,   52,
       52,   52,   52,   55,   52,   52,   52,   56,   52,   57,

       52,   52,   52,   28,   28,   28,   28,  122,  434,   28,
       58,   59,   58,   59,   72,   73,   74,  116,  154,  123,
       75,  131,  132,  117,   28,  124,  155,   61,   62,   60,
       28,   60,   61,   62,   65,   30,   83,   66,   28,   67,
      125,  134,   83,   84,  134,   68,   72,   73,   74,   84,
       85,   69,   75,  127,  128,  134,   85,  135,  134,  129,
      134,  169,  169,  433,  104,   70,  137,   71,   65,   30,
      104,   66,  194,   67,  139,  127,  169,  169,  195,   68,
      136,  127,  138,  182,  183,   69,  127,  128,  127,  128,
      127,  128,  129,  134,  129,  134,  129,  131,  132,   70,

      134,   71,   29,   30,  134,   77,  134,   78,   28,  127,
      203,  127,  128,   79,  207,  129,  252,  129,  204,   80,
      206,  104,  205,  233,  127,  134,  234,  104,  127,  128,
      127,  134,  127,   81,  129,   82,   29,   30,  127,   77,
      432,   78,   28,  251,  203,  253,  279,   79,  431,  129,
      280,  127,  291,   80,  134,  321,  291,  127,  254,  318,
      430,  319,  429,  320,  292,  428,  427,   81,  426,   82,
       28,   29,   30,   86,   31,   28,   32,   28,   87,   88,
       89,   90,   33,   90,   90,   90,   90,   91,   92,   93,
       90,   90,   90,   90,   94,   90,   95,   90,   90,   90,

       90,   90,   96,   90,   97,   90,   90,   90,   28,   29,
       30,   28,   31,   28,   98,   28,   28,   28,   28,  425,
       33,  424,  423,  422,  421,  420,  100,  134,  419,  418,
      417,  416,  415,  414,  413,  412,  411,  410,  409,  408,
      101,  407,  102,   28,   29,   30,   28,   31,   28,   98,
       28,   28,   28,   28,  322,   33,  406,  405,  404,  403,
      402,  100,  401,  400,  399,  398,  397,  396,  395,  394,
      393,  392,  391,  390,  389,  101,  388,  102,   64,   64,
       64,   64,   64,   64,   76,   76,   76,   76,   76,   76,
       99,   99,   99,   99,   99,   99,  104,  104,  387,  104,

      104,  104,  130,  130,  130,  133,  133,  133,  146,  146,
      386,  146,  146,  146,  148,  148,  385,  148,  148,  148,
      158,  384,  383,  158,  158,  158,  159,  159,  382,  159,
      159,  159,  175,  175,  201,  381,  201,  202,  202,  202,
      250,  380,  250,  379,  378,  377,  376,  375,  374,  373,
      372,  371,  348,  370,  369,  368,  367,  366,  365,  364,
      363,  362,  361,  360,  359,  358,  357,  356,  355,  354,
      353,  352,  351,  350,  349,  134,  348,  347,  346,  345,
      344,  343,  342,  341,  340,  339,  338,  337,  336,  335,
      334,  333,  332,  331,  330,  329,  328,  327,  326,  325,

      324,  323,  317,  316,  315,  314,  313,  312,  311,  310,
      309,  308,  307,  306,  305,  304,  303,  302,  301,  300,
      299,  298,  297,  296,  295,  294,  293,  134,  134,  290,
      289,  288,  287,  286,  285,  284,  283,  282,  281,  278,
      277,  276,  275,  274,  273,  272,  271,  270,  269,  268,
      267,  266,  265,  264,  263,  262,  261,  260,  259,  258,
      257,  256,  255,  134,  249,  248,  247,  246,  245,  244,
      243,  242,  241,  240,  239,  238,  237,  236,  235,  232,
      231,  230,  229,  228,  174,  227,  169,  226,  225,  224,
      223,  222,  221,  160,  220,  219,  218,  217,  216,  215,

      214,  149,  147,  213,  212,  211,  210,  209,  208,  134,
      134,  200,  199,  198,  197,  196,  193,  192,  189,  188,
      187,  186,  185,  184,  181,  180,  179,  105,  103,  178,
      177,  176,  174,  173,  172,  171,  170,  169,  167,  167,
      167,  166,  165,  164,  163,  162,  161,  106,  160,  157,
      156,  153,  152,  151,  150,  106,  149,  147,  145,  144,
      143,  142,  141,  140,  134,  123,  126,  121,  118,  113,
      112,  111,  108,  107,  106,  105,  103,  436,   28,   28,
       27,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,

      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436
    } ;

static yyconst short int yy_chk[720] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    3,   40,
       40,   43,   11,   12,    3,    3,    3,    3,    3,   11,
       12,   36,    3,  117,   36,    3,    3,  117,   43,    3,
      447,    3,  434,    3,    3,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,

        5,    5,    5,    7,    9,    8,   15,   45,  433,   10,
        7,    7,    8,    8,   15,   15,   15,   41,   73,   45,
       15,   51,   51,   41,   19,   46,   73,    9,    9,    7,
       20,    8,   10,   10,   13,   13,   19,   13,   16,   13,
       46,   53,   20,   19,   55,   13,   16,   16,   16,   20,
       19,   13,   16,   50,   50,   54,   20,   53,   57,   50,
       56,   93,   94,  431,   77,   13,   55,   13,   14,   14,
       77,   14,  120,   14,   57,  127,   93,   94,  120,   14,
       54,  127,   56,  110,  110,   14,  128,  128,  129,  129,
      130,  130,  128,  135,  129,  137,  130,  132,  132,   14,

      136,   14,   17,   17,  204,   17,  139,   17,   17,  131,
      131,  134,  134,   17,  139,  131,  204,  134,  135,   17,
      137,  159,  136,  182,  201,  205,  182,  159,  202,  202,
      201,  206,  250,   17,  202,   17,   18,   18,  250,   18,
      429,   18,   18,  203,  203,  205,  237,   18,  428,  203,
      237,  251,  251,   18,  252,  291,  291,  251,  206,  290,
      427,  290,  425,  290,  252,  424,  423,   18,  422,   18,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,

       23,   23,   23,   23,   23,   23,   23,   23,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,  419,
       25,  418,  416,  415,  414,  412,   25,  292,  411,  410,
      409,  408,  406,  405,  404,  402,  401,  400,  399,  398,
       25,  396,   25,   26,   26,   26,   26,   26,   26,   26,
       26,   26,   26,   26,  292,   26,  395,  394,  393,  392,
      390,   26,  388,  387,  386,  385,  384,  382,  379,  378,
      376,  375,  373,  372,  371,   26,  370,   26,  437,  437,
      437,  437,  437,  437,  438,  438,  438,  438,  438,  438,
      439,  439,  439,  439,  439,  439,  440,  440,  369,  440,

      440,  440,  441,  441,  441,  442,  442,  442,  443,  443,
      368,  443,  443,  443,  444,  444,  367,  444,  444,  444,
      445,  366,  365,  445,  445,  445,  446,  446,  364,  446,
      446,  446,  448,  448,  449,  363,  449,  450,  450,  450,
      451,  360,  451,  359,  358,  357,  356,  355,  353,  352,
      351,  349,  348,  347,  346,  345,  344,  343,  342,  341,
      339,  338,  337,  336,  335,  334,  332,  330,  329,  328,
      327,  326,  325,  324,  323,  322,  321,  320,  319,  318,
      317,  316,  314,  313,  312,  311,  310,  309,  308,  307,
      306,  305,  303,  302,  301,  299,  298,  297,  296,  295,

      294,  293,  288,  287,  286,  285,  284,  283,  282,  281,
      280,  279,  277,  276,  275,  274,  270,  268,  266,  265,
      264,  262,  259,  258,  257,  256,  255,  254,  253,  249,
      248,  247,  246,  244,  243,  242,  241,  240,  239,  236,
      235,  234,  233,  232,  231,  228,  226,  225,  224,  223,
      221,  220,  219,  218,  217,  216,  214,  213,  212,  211,
      210,  209,  208,  207,  199,  196,  195,  194,  193,  192,
      191,  190,  189,  188,  187,  186,  185,  184,  183,  181,
      180,  179,  178,  176,  174,  173,  171,  170,  166,  165,
      164,  163,  161,  160,  157,  156,  155,  154,  153,  152,

      150,  149,  147,  145,  144,  143,  142,  141,  140,  138,
      133,  126,  125,  124,  122,  121,  119,  118,  116,  115,
      114,  113,  112,  111,  109,  108,  107,  105,  103,  102,
      101,  100,   98,   97,   96,   95,   92,   91,   89,   87,
       86,   85,   84,   83,   82,   81,   80,   79,   78,   75,
       74,   72,   71,   70,   69,   68,   67,   65,   63,   62,
       61,   60,   59,   58,   52,   49,   47,   44,   42,   39,
       38,   37,   35,   34,   33,   32,   29,   27,   22,   21,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,

      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "config_scan.l"
#define INITIAL 0
/*
 * Copyright (c) 1997, 1998
 *      Inferno Nettverk A/S, Norway.  All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. The above copyright notice, this list of conditions and the following
 *    disclaimer must appear in all copies of the software, derivative works
 *    or modified versions, and any portions thereof, aswell as in all
 *    supporting documentation.
 * 2. All advertising materials mentioning features or use of this software
 *    must display the following acknowledgement:
 *      This product includes software developed by
 *      Inferno Nettverk A/S, Norway.
 * 3. The name of the author may not be used to endorse or promote products
 *    derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. 
 * IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT 
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * Inferno Nettverk A/S requests users of this software to return to
 * 
 *  Software Distribution Coordinator  or  sdc@inet.no
 *  Inferno Nettverk A/S
 *  Oslo Research Park
 *  Gaustadaléen 21
 *  N-0371 Oslo
 *  Norway
 * 
 * any improvements or extensions that they make and grant Inferno Nettverk A/S
 * the rights to redistribute these changes.
 *
 */
#line 45 "config_scan.l"

static const char rcsid[] =
"$Id: config_scan.l,v 1.32 1998/12/08 19:34:23 michaels Exp $";

#include "common.h"

#include "yacconfig.h" 
#include "config_parse.h"


/* %option debug */
/* startconditions */
#define lineprefix 1

#define start_address 2

#define start_command 3

#define start_compatibility 4

#define start_extension 5

#define start_line 6

#define start_log 7

#define start_logoutput 8

#define start_method 9

#define start_option 10

#define start_service 11

#define start_username 12

#line 815 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#ifdef __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 76 "config_scan.l"



	/*
	 * we can operate in more than one mode, find out which it is and
	 * let the parser know.
	*/



	extern int parseinit;
	extern const int configtype;

	if (!parseinit) {
		parseinit = 1;

		switch (configtype) {
			case CONFIGTYPE_SERVER:
				return SERVERCONFIG;

			case CONFIGTYPE_CLIENT:
				return CLIENTCONFIG;

			default:
				SERR(configtype);
		}
	}


	/*
	 * Config stuff. 
	*/




	/* generic */

#line 1005 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 437 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 681 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 114 "config_scan.l"
{
	yylval.string = yytext;
	return DEBUGING;
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 119 "config_scan.l"
{
	yylval.string = yytext;
	return ROUTE;
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 125 "config_scan.l"
{
	yylval.string = yytext;
	return PROTOCOLVERSION;
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 131 "config_scan.l"
{
	BEGIN(start_logoutput);

	yylval.string = yytext;
	return LOGOUTPUT;
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 138 "config_scan.l"
{
	yylval.string = yytext;
	return LOGFILE;
}
	YY_BREAK
/*
	 * protocol
	 */
case 6:
YY_RULE_SETUP
#line 147 "config_scan.l"
{
	yylval.string = yytext;
	return PROTOCOL; 
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 153 "config_scan.l"
{
	yylval.string = yytext;
	return PROTOCOL_TCP;
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 158 "config_scan.l"
{
	yylval.string = yytext;
	return PROTOCOL_UDP;
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 163 "config_scan.l"
{
	BEGIN(start_command);

	yylval.string = yytext;
	return COMMAND; 
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 170 "config_scan.l"
{
	yylval.string = yytext;
	return COMMAND_BIND; 
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 175 "config_scan.l"
{
	yylval.string = yytext;
	return COMMAND_CONNECT; 
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 180 "config_scan.l"
{
	yylval.string = yytext;
	return COMMAND_UDPASSOCIATE;
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 185 "config_scan.l"
{
	yylval.string = yytext;
	return COMMAND_BINDREPLY;
}
	YY_BREAK
/*
	 * addresses
	 */
case 14:
YY_RULE_SETUP
#line 196 "config_scan.l"
{
	BEGIN(start_address);

	yylval.string = yytext;
	return FROM; 
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 203 "config_scan.l"
{
	BEGIN(start_address);

	yylval.string = yytext;
	return TO; 
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 210 "config_scan.l"
{
	BEGIN(start_address);

	yylval.string = yytext;
	return VIA; 
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 219 "config_scan.l"
{ 
	yylval.string = yytext;
	return IPADDRESS; 
}
	YY_BREAK
/* XXX check rfc for what constitutes a valid domain */
case 18:
YY_RULE_SETUP
#line 225 "config_scan.l"
{
	yylval.string = yytext;
	return DOMAIN;
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 230 "config_scan.l"
{
	yylval.string = yytext;
	return DIRECT;
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 236 "config_scan.l"
{
	BEGIN(start_service);

	yylval.string = yytext;
	return PORT; 
}
	YY_BREAK
/* compare */
case 21:
YY_RULE_SETUP
#line 244 "config_scan.l"
{
	yylval.string = yytext;
	return OPERATOR; 
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 249 "config_scan.l"
{
	BEGIN(0);

	yylval.string = yytext;
	return SERVICENAME;
}
	YY_BREAK
/*
	 * authentication
	*/
case 23:
YY_RULE_SETUP
#line 262 "config_scan.l"
{
	BEGIN(start_method);	/* identical names to method */

	yylval.string = yytext;
	return AUTH; 
}
	YY_BREAK
/* server configstuff */
case 24:
YY_RULE_SETUP
#line 274 "config_scan.l"
{
	BEGIN(start_address);

	yylval.string = yytext;
	return INTERNAL;
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 281 "config_scan.l"
{
	BEGIN(start_address);

	yylval.string = yytext;
	return EXTERNAL;
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 289 "config_scan.l"
{

	yylval.string = yytext;
	return PRIVILEGED;
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 295 "config_scan.l"
{
	BEGIN(start_username);

	yylval.string = yytext;
	return USER_PRIVILEGED;
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 302 "config_scan.l"
{
	BEGIN(start_username);

	yylval.string = yytext;
	return USER_UNPRIVILEGED;
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 309 "config_scan.l"
{
	BEGIN(start_username);

	yylval.string = yytext;
	return USER_LIBWRAP;
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 317 "config_scan.l"
{
	BEGIN(0);
	
	yylval.string = yytext;
	return USERNAME;
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 324 "config_scan.l"
{
	yylval.string = yytext;
	return IOTIMEOUT;
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 329 "config_scan.l"
{
	BEGIN(start_compatibility);

	yylval.string = yytext;
	return COMPATIBILITY;
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 336 "config_scan.l"
{
	yylval.string = yytext;
	return REUSEADDR;
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 341 "config_scan.l"
{
	yylval.string = yytext;
	return SAMEPORT;
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 347 "config_scan.l"
{
	yylval.string = yytext;
	return CONNECTTIMEOUT;
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 352 "config_scan.l"
{
	BEGIN(start_extension);

	yylval.string = yytext;
	return EXTENSION;
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 360 "config_scan.l"
{
	yylval.string = yytext;
	return BIND;
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 367 "config_scan.l"
{
	yylval.string = yytext;
	return CLIENT;
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 373 "config_scan.l"
{
	BEGIN(start_method);

	yylval.string = yytext;
	return METHOD;
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 380 "config_scan.l"
{
	yylval.string = yytext;
	return NONE;
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 385 "config_scan.l"
{
	yylval.string = yytext;
	return GSSAPI;
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 390 "config_scan.l"
{
	yylval.string = yytext;
	return UNAME;
}
	YY_BREAK
/* filterrules */
/*
	 * verdicts
 	*/
case 43:
YY_RULE_SETUP
#line 402 "config_scan.l"
{
	yylval.string = yytext;
	return VERDICT_BLOCK;
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 407 "config_scan.l"
{
	yylval.string = yytext;
	return VERDICT_PASS;
}
	YY_BREAK
/*
	 * logging 
	 */
case 45:
YY_RULE_SETUP
#line 418 "config_scan.l"
{
	BEGIN(start_log);

	yylval.string = yytext;
	return LOG;  
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 425 "config_scan.l"
{
	yylval.string = yytext;
	return LOG_CONNECT;
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 430 "config_scan.l"
{
	yylval.string = yytext;
	return LOG_DATA;
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 435 "config_scan.l"
{
	yylval.string = yytext;
	return LOG_DISCONNECT;
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 440 "config_scan.l"
{
	yylval.string = yytext;
	return LOG_ERROR;
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 445 "config_scan.l"
{
	yylval.string = yytext;
	return LOG_IOOPERATION;
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 450 "config_scan.l"
{
	BEGIN(lineprefix); 

	yylval.string = yytext;
	return LIBWRAPSTART;
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 457 "config_scan.l"
{
	BEGIN(lineprefix); 

	yylval.string = yytext;
	return LOCALDOMAIN;  
}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 464 "config_scan.l"
{
	BEGIN(start_line);

	yylval.string = yytext;
	return *yytext;
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 471 "config_scan.l"
{
	BEGIN(0);

	yylval.string = yytext;
	return LINE;
}
	YY_BREAK
/* misc generic stuff. */
case 55:
YY_RULE_SETUP
#line 485 "config_scan.l"
{
	yylval.string = yytext;
	return NUMBER;
}
	YY_BREAK
/* ignored */
case 56:
YY_RULE_SETUP
#line 492 "config_scan.l"
{
	;
}
	YY_BREAK
/* shell style comment */
case 57:
YY_RULE_SETUP
#line 497 "config_scan.l"
{
	;
}
	YY_BREAK
/* state always ends at eol. */
case 58:
YY_RULE_SETUP
#line 502 "config_scan.l"
{
	BEGIN(0);
}
	YY_BREAK
/* unless it's escaped. */
case 59:
YY_RULE_SETUP
#line 507 "config_scan.l"
{
	;
}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 511 "config_scan.l"
{
	return *yytext;
}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 516 "config_scan.l"
ECHO;
	YY_BREAK
#line 1645 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
			case YY_STATE_EOF(lineprefix):
			case YY_STATE_EOF(start_address):
			case YY_STATE_EOF(start_command):
			case YY_STATE_EOF(start_compatibility):
			case YY_STATE_EOF(start_extension):
			case YY_STATE_EOF(start_line):
			case YY_STATE_EOF(start_log):
			case YY_STATE_EOF(start_logoutput):
			case YY_STATE_EOF(start_method):
			case YY_STATE_EOF(start_option):
			case YY_STATE_EOF(start_service):
			case YY_STATE_EOF(start_username):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 437 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 437 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 436);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 516 "config_scan.l"
