.Dd November 13, 1998
.Dt SOCKD 8
.Sh NAME
.Nm sockd
.Nd Relay data and firewall network
.Sh SYNOPSIS
.Nm sockd
.Op Fl Ddhlv
.Oo
.Fl f Ar file
.Oc
.Oo
.Fl n Ar number
.Oc
.Sh DESCRIPTION
.Nm Dante
implements the Socks standard and functions as a firewall between networks. 
.Pp
It relays TCP and UDP both from outside the network and in, and from inside
and out.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl D
.Nm Dante
will detach itself from the controlling terminal and run in
the background as system daemons.
.It Fl L
Displays the license
.Nm Dante
comes under.
.It Fl d
Enables debugging.
.It Fl h
Shows the currently valid options.
.It Fl l
The log output from 
.Nm Dante
will be linebuffered.
.It Fl v
Displays versioninfo for 
.Nm Dante.
.It Fl f Ar file
.Nm Dante
will read its configuration from
.Ar file .
.It Fl n Ar number
.Nm Dante
will fork of 
.Ar number
copies of itself when starting.  Can be used for very busy servers.
.Sh FILES
.Pa /etc/sockd.conf
.Sh SEE ALSO
Information about new releases and other related issues can be found
on the Dante WWW home page at http://www.inet.no/dante.
.Sh AUTHORS
Michael Shuldman <michaels@inet.no>
.Pp
Karl-André Skevik <karls@inet.no>
.Sh BUGS
See the accompanying BUGS file.  New ones should be reported to
dante\-bugs@inet.no.
